{{- include "adp-helm-library.deployment" (list . "test-backend-8.deployment") -}}
{{- define "test-backend-8.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "adp-helm-library.container" (list . "test-backend-8.container") }}
{{- end -}}
